# isRuntimeException

Returns `true` if the specified value is an `RuntimeException`, `false`
otherwise.

To import and use `isRuntimeException` from the "Cause" module:

ts
import \* as Cause from "effect/Cause"
// Can be accessed like this
Cause.isRuntimeException
undefined

**Signature**

```ts
export declare const isRuntimeException: (u: unknown) => u is RuntimeException
```
